### ISSUE TITLE
Update cats version from master brach

### ISSUE THREAD

**Issue by fagossa** [fagossa/tutorial-cats#4]
I already migrated the cats version deom the *solution* branch.

The same changes should be done to the *master* branch

**Comment by baddoub** [comment]
I did the changes and upgraded the Scala and sbt versions by the way. But I'm stuck with no right to push PRs ^^.

**Comment by fagossa** [comment]
It should be ok now

**Comment by baddoub** [comment]
Fixed by https://github.com/fagossa/tutorial-cats/pull/5
